# Define the port where the Widget Foundry server would be running
server:
  port: 9006

# Define the Eureka server that handles service registration
eureka:
  instance:
      hostname: localhost
      port: 8761
      leaseRenewalIntervalInSeconds: 5
      lease-expiration-duration-in-seconds: 5
      metadataMap:
       cluster: MYCLUSTER
       instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/


spring:
  profiles: docker

server:
  port: ${SERVICE_PORT}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${REGISTRY_URL}

environments:
    path:
        wkhtml: /opt/wkhtmltox/bin/wkhtmltopdf
